"""Configuration for pytest-aitest Excel tool tests.

These tests validate that LLMs can correctly use the Excel tool schemas
generated by the codegen system. They use the real production system prompt
and tool manifest.

Run with: uv run pytest tests-aitest/ -v
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

from pytest_aitest import MCPServer, Wait

# ---------------------------------------------------------------------------
# Environment setup
# ---------------------------------------------------------------------------

# LiteLLM bug workaround: their logging code expects AZURE_API_BASE but
# Azure SDK uses AZURE_OPENAI_ENDPOINT. Set both to silence the warning.
if os.environ.get("AZURE_OPENAI_ENDPOINT") and not os.environ.get("AZURE_API_BASE"):
    os.environ["AZURE_API_BASE"] = os.environ["AZURE_OPENAI_ENDPOINT"]


def pytest_configure(config: pytest.Config) -> None:
    """Configure pytest-llm-assert to use Azure."""
    azure_base = os.environ.get("AZURE_API_BASE") or os.environ.get("AZURE_OPENAI_ENDPOINT")
    if azure_base:
        config.option.llm_model = "azure/gpt-5-mini"
        config.option.llm_api_base = azure_base


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Default model for tests (cheapest Azure deployment)
DEFAULT_MODEL = "gpt-5-mini"

# Rate limits for Azure deployments
DEFAULT_RPM = 10
DEFAULT_TPM = 10000

# Default turn limits
DEFAULT_MAX_TURNS = 5

# Paths (relative to this project)
_PROJECT_ROOT = Path(__file__).parent.parent
MANIFEST_PATH = _PROJECT_ROOT / "src" / "tools" / "tools-manifest.json"
SYSTEM_PROMPT_PATH = _PROJECT_ROOT / "src" / "services" / "ai" / "SYSTEM_PROMPT.md"


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def excel_server():
    """Excel MCP server backed by in-memory simulator."""
    if not MANIFEST_PATH.exists():
        pytest.skip(f"Manifest not found: {MANIFEST_PATH}. Run 'npm run manifest' first.")

    return MCPServer(
        command=[
            sys.executable,
            "-u",
            str(Path(__file__).parent / "excel_mcp.py"),
            "--manifest",
            str(MANIFEST_PATH),
        ],
        wait=Wait.for_tools(["get_range_values", "set_range_values", "list_sheets"]),
    )
